project:
  type: book

book:
  title: "30 Day Coding Challenge"
  author: "Jim Grange"
  # cover-image: images/custom/prompts.png
  # image: images/custom/prompts.png
  chapters:
    - index.qmd
    - part: "comparisons"
      chapters: 
        - intro.qmd
        - summary.qmd
    - part: "distributions"
      chapters: 
        - intro.qmd
        - summary.qmd
        - references.qmd
  # sidebar:
  #   style: docked
  #   background: white
bibliography: references.bib

format:
  html:
    theme: 
      light: yeti
      dark: darkly
    code-link: true
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    code-copy: true
    # code-block-border-left: "#4864DB"
    highlight-style: a11y
    # monofont: Fira Code
    # mainfont: Open Sans
    css: include/style.css
    
editor: visual
