project:
  type: book
  output-dir: docs
  
book:
  title: "30 Day Coding Challenge (2023)"
  author: "Jim Grange"
  # cover-image: images/custom/prompts.png
  # image: images/custom/prompts.png
  chapters:
    - index.qmd
    - part: "Comparisons"
      chapters: 
        - chapters/part-to-whole.qmd
    # - part: "Distributions"
    #   chapters: 
    #     - blank.qmd
    #     - blank.qmd
        # - blank.qmd
    - part: references.qmd
  # sidebar:
  #   style: docked
  #   background: white
bibliography: references.bib

format:
  html:
    theme: 
      light: yeti
      dark: darkly
    code-link: true
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    code-copy: true
    code-block-bg: "#D1D9CE80"
    code-block-border-left: "#D1D9CE"
    highlight-style: a11y
    # monofont: Fira Code
    # mainfont: Open Sans
    css: include/style.css
    
editor: visual
